### ISSUE TITLE
nodetool fails due to `tderr: error: 'java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)'`

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylla-tools-java#374]
```
ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/61395a3658acbe786928090913b047373cea21fa/share/cassandra/bin/nodetool -h 127.0.60.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy help exited with non-zero status; exit status: 2; 
stderr: error: 'java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)'
-- StackTrace --
java.lang.NoSuchMethodError: 'java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)'
	at io.airlift.command.GlobalUsageSummary$2.apply(GlobalUsageSummary.java:100)
	at io.airlift.command.GlobalUsageSummary$2.apply(GlobalUsageSummary.java:97)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:829)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
	at io.airlift.command.UsagePrinter.appendTable(UsagePrinter.java:57)
	at io.airlift.command.GlobalUsageSummary.usage(GlobalUsageSummary.java:96)
	at io.airlift.command.GlobalUsageSummary.usage(GlobalUsageSummary.java:52)
	at io.airlift.command.Help.help(Help.java:57)
	at io.airlift.command.Help.help(Help.java:50)
	at io.airlift.command.Help.run(Help.java:25)
	at org.apache.cassandra.tools.NodeTool$CassHelp.run(NodeTool.java:257)
	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:196)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:62)
```

irst seen in [https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/464/testRe[…]chines___FullDtest___full_split012___test_rolling_upgrade/](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/464/testReport/rolling_upgrade_test/TestRollingUpgrade/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split012___test_rolling_upgrade/)

**Comment by tchaikov** [comment]
it is a regression introduced by 43427dfa which intended to address #365

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint Please backport this
